version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  yt-worker:
    image: Akshit8/yt-worker
    env_file: .env

  api:
    image: Akshit8/yt-search-django
    ports:
      - 8000:8000
    environment: .env