version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  yt-worker:
    image: akshit8/yt-worker
    env_file: .env
    depends_on: 
      - elasticsearch


  api:
    image: akshit8/yt-search-django
    ports:
      - 8000:8000
    environment:
      ELASTICSEARCH_HOST: elasticsearch:9200
    depends_on: 
      - elasticsearch