version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200 || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - discovery.type=single-node

  api:
    image: akshit8/yt-search-django
    ports:
      - 8000:8000
    environment:
      ELASTICSEARCH_HOST: elasticsearch:9200
    depends_on: 
      - elasticsearch