name: build and push app image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: docker login
        run: |
          docker login -u ${{secrets.USERNAME}} -p ${{secrets.PASSWORD}}
      
      - name: build worker image
        run: |
          docker build -t akshit8/yt-worker ./yt

      - name: build api image
        run: |
          docker build -t akshit8/yt-search-django .

      - name: push worker image
        run: |
          docker push akshit8/yt-worker

      - name: push api image
        run: |
          docker push akshit8/yt-search-django